-- Active: 1670112448047@@127.0.0.1@3306
DROP DATABASE IF EXISTS UNIVERSITY_ROOM_BOOKING;
CREATE DATABASE UNIVERSITY_ROOM_BOOKING;
USE UNIVERSITY_ROOM_BOOKING;


CREATE TABLE PERSON(
    PersonID INTEGER PRIMARY KEY AUTOINCREMENT;
    FirstName VARCHAR(255) NOT NULL;
    MInit VARCHAR;
    LastName VARCHAR(255) NOT NULL;
    PhoneNumber VARCHAR(255) NOT NULL;
    Email VARCHAR(255) NOT NULL;
)

CREATE TABLE STUDENT